services:
  techlabify-dnsmasq:
    build: .
    container_name: techlabify-dnsmasq
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq-static.leases:/etc/dnsmasq-static.leases
      - ./dnsmasq.leases:/var/lib/misc/dnsmasq.leases
    restart: unless-stopped
